/**
 * type = 1 is Switch
 * type = 2 is TextInput
 */
export const BUG_LIST = [
  {
    id: 'ER0000',
    label: 'Không Lỗi',
    type: 1,
    name: 'khongLoi',
    defaultValue: false,
  },
  {
    id: 'ER0001',
    label: 'Mã vạch',
    type: 2,
    name: 'maVach',
    defaultValue: '',
  },
  {
    id: 'ER0002',
    label: 'Dơ, bẩn',
    type: 1,
    name: 'doBan',
    defaultValue: false,
  },
  {
    id: 'ER0003',
    label: 'Móp/nhăn',
    type: 1,
    name: 'mopNhan',
    defaultValue: false,
  },
  {
    id: 'ER0004',
    label: 'Thủng',
    type: 1,
    name: 'thung',
    defaultValue: false,
  },
  {
    id: 'ER0005',
    label: 'Màu in',
    type: 2,
    name: 'mauIn',
    defaultValue: '',
  },
  {
    id: 'ER0006',
    label: 'Chữ in',
    type: 2,
    name: 'chuIn',
    defaultValue: '',
  },
  {
    id: 'ER0007',
    label: 'In tràn đường cắt',
    type: 1,
    name: 'inTranDuongCat',
    defaultValue: false,
  },
  {
    id: 'ER0008',
    label: 'Thiếu bộ phận',
    type: 1,
    name: 'thieuBoPhan',
    defaultValue: false,
  },
  {
    id: 'ER0009',
    label: 'Sai bộ phận',
    type: 1,
    name: 'saiBoPhan',
    defaultValue: false,
  },
  {
    id: 'ER0010',
    label: 'Bụi',
    type: 1,
    name: 'bui',
    defaultValue: false,
  },
  {
    id: 'ER0011',
    label: 'Trầy xước',
    type: 1,
    name: 'trayXuoc',
    defaultValue: false,
  },
  {
    id: 'ER0012',
    label: 'Lệch trọng lượng',
    type: 1,
    name: 'lechTrongLuong',
    defaultValue: false,
  },
  {
    id: 'ER0013',
    label: 'Vị trí nhãn',
    type: 2,
    name: 'viTriNhan',
    defaultValue: '',
  },
  {
    id: 'ER0014',
    label: 'Mã sản xuất bị thiếu/không đọc được/vị trí',
    type: 1,
    name: 'maSanXuatBiThieu',
    defaultValue: false,
  },
  {
    id: 'ER0015',
    label: 'Mở nắp',
    type: 1,
    name: 'moNap',
    defaultValue: false,
  },
  {
    id: 'ER0016',
    label: 'Cảm quan',
    type: 2,
    name: 'camQuan',
    defaultValue: '',
  },
  {
    id: 'ER0017',
    label: 'Màu sắc/tách/lắng đọng sản phẩm',
    type: 2,
    name: 'mauSac',
    defaultValue: '',
  },
  {
    id: 'ER0018',
    label: 'Vât lạ',
    type: 2,
    name: 'vatLa',
    defaultValue: '',
  },
  {
    id: 'ER0019',
    label: 'Hư seal',
    type: 1,
    name: 'huSeal',
    defaultValue: false,
  },
  {
    id: 'ER0020',
    label: 'Vật sắc',
    type: 1,
    name: 'vatSac',
    defaultValue: false,
  },
  {
    id: 'ER0021',
    label: 'Nứt',
    type: 1,
    name: 'nut',
    defaultValue: false,
  },
  {
    id: 'ER0022',
    label: 'Tách lớp',
    type: 1,
    name: 'tachLop',
    defaultValue: false,
  },
  {
    id: 'ER0023',
    label: 'Chiều cao sản phẩm bên trong',
    type: 2,
    name: 'chieuCao',
    defaultValue: '',
  },
  {
    id: 'ER0024',
    label: 'Độ dính nhãn',
    type: 2,
    name: 'doDinhNhan',
    defaultValue: '',
  },
  {
    id: 'ER0025',
    label: 'Hư nắp',
    type: 1,
    name: 'huNap',
    defaultValue: false,
  },
  {
    id: 'ER0026',
    label: 'Rách bộ phận mở hình chữ V',
    type: 1,
    name: 'rachBoPhanChuV',
    defaultValue: false,
  },
  {
    id: 'ER0027',
    label: 'Thiết bị mở bị rách',
    type: 1,
    name: 'thietBiMoBiRach',
    defaultValue: false,
  },
  {
    id: 'ER0028',
    label: 'Bám đá',
    type: 1,
    name: 'bamDa',
    defaultValue: false,
  },
  {
    id: 'ER0029',
    label: 'Vị trí seal',
    type: 2,
    name: 'viTriSeal',
    defaultValue: '',
  },
  {
    id: 'ER0030',
    label: 'Dư',
    type: 1,
    name: 'du',
    defaultValue: false,
  },
  {
    id: 'ER0031',
    label: 'Bung gói',
    type: 1,
    name: 'bungGoi',
    defaultValue: false,
  },
  {
    id: 'ER0032',
    label: 'Keo dính',
    type: 1,
    name: 'keoDinh',
    defaultValue: false,
  },
  {
    id: 'ER0033',
    label: 'Bong bóng khí',
    type: 1,
    name: 'bongBongKhi',
    defaultValue: false,
  },
  {
    id: 'ER0034',
    label: 'Phồng',
    type: 1,
    name: 'phong',
    defaultValue: false,
  },
  {
    id: 'ER0035',
    label: 'Hở seal',
    type: 1,
    name: 'hoSeal',
    defaultValue: false,
  },
  {
    id: 'ER0036',
    label: 'Lệch seal',
    type: 1,
    name: 'lechSeal',
    defaultValue: false,
  },
  {
    id: 'ER0037',
    label: 'Rò rỉ',
    type: 1,
    name: 'roRi',
    defaultValue: false,
  },
  {
    id: 'ER0038',
    label: 'Hư nhãn',
    type: 1,
    name: 'huNhan',
    defaultValue: false,
  },
  {
    id: 'ER0039',
    label: 'Bám nắp',
    type: 1,
    name: 'bamNap',
    defaultValue: false,
  },
  {
    id: 'ER0040',
    label: 'Bung',
    type: 1,
    name: 'bung',
    defaultValue: false,
  },
  {
    id: 'ER0041',
    label: 'Hư chốt',
    type: 1,
    name: 'huChot',
    defaultValue: false,
  },
  {
    id: 'ER0042',
    label: 'Khoá',
    type: 1,
    name: 'khoa',
    defaultValue: false,
  },
  {
    id: 'ER0043',
    label: 'Lệch vòi',
    type: 1,
    name: 'lechVoi',
    defaultValue: false,
  },
  {
    id: 'ER0044',
    label: 'Loang nhựa',
    type: 1,
    name: 'loangNhua',
    defaultValue: false,
  },
  {
    id: 'ER0045',
    label: 'Đốm đen',
    type: 1,
    name: 'domDen',
    defaultValue: false,
  },
  {
    id: 'ER0046',
    label: 'Hỏng bao bì',
    type: 1,
    name: 'hongBaoBi',
    defaultValue: false,
  },
];
